project:
  type: website

resources:
  - CNAME
  - documentation/slides/*.zip
  - documentation/2026-02-26-tidyR-omicsws1/*.zip
  - documentation/2026-02-26-tidyR-omicsws1/*.html
  - documentation/2026-03-26-bulk-omicsws2/*
  - documentation/2026-04-13-yoda-R/*
  - documentation/2026-04-23-omicsws3/scRNA_workshop.zip

website:
  title: 'ABC - Accessible Bioinformatics Cafe'
  google-analytics: 
    tracking-id: "G-WG01Z2LJ1J"
    anonymize-ip: true
  open-graph:
    locale: en_US
    site-name: ABC - Accessible Bioinformatics Cafe
  navbar:
    logo: /img/focusgroup_logo.svg
    left:
      - href: index.qmd
        text: Home

      #- href: Documentation.qmd
      #  text: Documentation
      - text: Legacy
        menu:
          - href: Documentation.qmd
            text: Documentation
          - href: news.qmd
            text: Calendar
          #- href: binfResources/R.qmd
          #  text: R
          #- href: binfResources/python.qmd
          #  text: Python
      - href: gethelp.qmd
        text: People&Help
    right: 
      - icon: github
        href: https://github.com/AU-ABC
        aria-label: GitHub


format:
  html:
    theme: 
      light: [cosmo, css/au-light.scss]
      dark: [darkly, css/au-dark.scss]
    toc: true
    include-in-header:
      - file: "resources/mailerlite.html"
