project:
  type: website

resources:
  - CNAME

website:
  title: 'ABC - Accessible Bioinformatics Cafe'
  navbar:
    logo: /img/ABClogo.png
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
      - text: Tips
        menu:
          - href: tips/bash.qmd
          - href: tips/R.qmd
          - href: tips/python.qmd
    right: 
      - icon: github
        href: https://github.com/AU-ABC
        aria-label: GitHub
#      - icon: linkedin
#        href: https://www.linkedin.com/company/ucph-heads
#        aria-label: LinkedIn
#      - icon: twitter
#        href: https://twitter.com/ucph_heads
#        aria-label: Twitter   


format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
#    include-in-header:
#      - file: "resources/bioschema.html"
