project:
  type: website
  pre-render: resources/build_ics.py

resources:
  - CNAME
  - events/events.json
  - events/abc-events.ics
  - documentation/slides/*.zip
  - legacy/documentation/2026-02-26-tidyR-omicsws1/*.zip
  - legacy/documentation/2026-02-26-tidyR-omicsws1/*.html
  - legacy/documentation/2026-03-26-bulk-omicsws2/*
  - legacy/documentation/2026-04-13-yoda-R/*
  - legacy/documentation/2026-04-23-omicsws3/scRNA_workshop.zip

website:
  title: 'ABC - Accessible Bioinformatics Cafe'
  google-analytics: 
    tracking-id: "G-WG01Z2LJ1J"
    anonymize-ip: true
  open-graph:
    locale: en_US
    site-name: ABC - Accessible Bioinformatics Cafe
  navbar:
    logo: /img/focusgroup_logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: calendar.qmd
        text: Calendar
      - text: Legacy
        menu:
          - href: legacy/Documentation.qmd
            text: Old cafe tutorials
          - href: legacy/news.qmd
            text: Old cafe events
      - href: contact.qmd
        text: Contact
    right: 
      - icon: github
        href: https://github.com/AU-ABC
        aria-label: GitHub


format:
  html:
    theme: 
      light: [cosmo, css/au-light.scss]
      dark: [darkly, css/au-dark.scss]
    toc: true
    include-in-header:
      - file: "resources/mailerlite.html"
