project:
  type: website

resources:
  - CNAME
  - documentation/slides/*.zip

website:
  title: 'ABC - Accessible Bioinformatics Cafe'
  google-analytics: 
    tracking-id: "G-WG01Z2LJ1J"
    anonymize-ip: true
  open-graph:
    locale: en_US
    site-name: ABC - Accessible Bioinformatics Cafe
  navbar:
    logo: /img/ABClogo.png
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: Calendar
      - href: Documentation.qmd
        text: Documentation
      - text: Resources
        menu:
          #- href: binfResources/Databases.ipynb
          #  text: Databases
          - href: binfResources/bash.qmd
            text: Bash tips
          #- href: binfResources/R.qmd
          #  text: R
          #- href: binfResources/python.qmd
          #  text: Python
      - href: gethelp.qmd
        text: People&Help
    right: 
      - icon: github
        href: https://github.com/AU-ABC
        aria-label: GitHub


format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
    include-in-header:
      - file: "resources/mailerlite.html"
