name: Daily Database Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches: main
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install required Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests lxml beautifulsoup4

      # Step 4: Download the Excel file from Google Drive
      - name: Download Excel File
        run: |
          curl -L -o downloaded_file.xlsx  "https://docs.google.com/spreadsheets/d/1AQa2f94s1WrNMXutVVvpeLuPFcCcNDe4/export?format=xlsx"

      # Step 5: Process the Excel file
      - name: Process Excel File
        run: |
          python resources/databaseFetch.py

      # Step 6: Move the CSV to the desired folder
      - name: Move CSV to Target Folder
        run: |
          mv converted_file.csv resources/databases.csv

      # Step 7: Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 777 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Step 8: Commit and push changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "SamueleSoraggi"
          git config user.email "samuelson1990@gmail.com"
          git remote set-url origin git@github.com:AU-ABC/AU-ABC.github.io.git
          git add resources/databases.csv
          git commit -m "Update databases.csv"
          git push
