on: 
  push:
    branches: main
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Check out repository
        uses: actions/checkout@v4

#      - name: Install R
#        uses: r-lib/actions/setup-r@v2

#      - name: Install R packages
#        if: runner.os == 'Linux'
#        run: R -e "install.packages( c('openxlsx','knitr','rmarkdown') )"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        with:
          tinytex: true
          version: 1.4.515

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages